# Generated by Django 4.2.7 on 2023-12-08 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('DeptNo', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Dname', models.CharField(max_length=100, unique=True)),
                ('Loction', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('Ename', models.CharField(max_length=100)),
                ('Eid', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('Sal', models.IntegerField(max_length=10)),
                ('DeptNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
